/**
 * Surface du pont de données de l'édition web (window.electronAPI, nom
 * hérité de l'ancienne édition bureau). Utilisée par le stub précoce
 * (layout) qui met en attente les appels tant que le pont n'est pas prêt.
 */
export const ELECTRON_API_NAMES = [
  'getData', 'setData', 'clearData', 'getAllKeys',
  'openFileDialog', 'saveCasierFile', 'deleteCasierFile', 'openExternalFile', 'openExternalUrl',
  'saveFile', 'readFile', 'listFiles', 'deleteFile', 'saveFileDialog',
  'copyDataJson', 'restoreDataJson', 'getDataJsonInfo', 'compareWithDataJson',
  'listDataJsonBackups', 'getBackupStats', 'cleanOldBackups',
  'saveDocuments', 'copyToExternalPath', 'validatePath', 'selectFolder',
  'serverConfig_get', 'serverConfig_setup', 'serverConfig_reset',
  'openExternalFolder', 'deleteFromExternalPath', 'syncDocuments', 'scanForNewDocuments',
  'deleteDocument', 'openDocument', 'documentExists', 'getDocumentSize',
  'extractPDFText', 'scanExternalPDFs',
  'dataSync_checkAccess', 'dataSync_pull', 'dataSync_push', 'dataSync_backupServer',
  'dataSync_deleteServerBackup', 'dataSync_listServerBackups', 'dataSync_readServerBackup',
  'getCurrentUser',
  'dataSync_pullUsersConfig', 'dataSync_pushUsersConfig',
  'globalSync_pullTags', 'globalSync_pushTags',
  'globalSync_pullAudience', 'globalSync_pushAudience',
  'globalSync_pullAlerts', 'globalSync_pushAlerts',
  'globalSync_pullDeletedIds', 'globalSync_pushDeletedIds',
  'globalSync_pullCartographie', 'globalSync_pushCartographie',
  'globalSync_pullCartographieConfig', 'globalSync_pushCartographieConfig',
  'globalSync_pullAIRConfig', 'globalSync_pushAIRConfig',
  'globalSync_pullCartographieContributions', 'globalSync_pushCartographieContributions',
  'globalSync_readLegacyAppData',
  'globalSync_pullUserPreferences', 'globalSync_pushUserPreferences',
  'globalSync_pullContentieuxAlerts', 'globalSync_pushContentieuxAlerts',
  'dataSync_listAdminBackups', 'dataSync_restoreAdminBackup',
  'dataSync_checkContentieuxAccess',
  'paths_getEffective', 'paths_migrateContentieux', 'paths_migrateGeneral',
  'dataSync_pullContentieux', 'dataSync_pushContentieux', 'dataSync_backupContentieux',
  'dataSync_listContentieuxBackups', 'dataSync_readContentieuxBackup',
  'instructionSync_check', 'instructionSync_pull', 'instructionSync_push',
  'instructionSync_listBackups', 'instructionSync_readBackup', 'instructionSync_listUsers',
  'airSync_check', 'airSync_pull', 'airSync_push',
  'airSync_listBackups', 'airSync_readBackup', 'airSync_listUsers',
  'writeHeartbeat', 'removeHeartbeat', 'readAllHeartbeats',
  'writeSharedEvent', 'cleanupSharedEvents', 'startEventsWatcher', 'onSharedEvent',
  'readRecentSharedEvents',
  'startNetworkMonitor', 'stopNetworkMonitor', 'probeNetwork', 'getNetworkStatus', 'onNetworkStatus',
  'appendAuditLog', 'readAuditLog',
  'checkAppUpdate', 'applyAppUpdate', 'getUpdateChangelog',
  'e2ee_myScopes', 'e2ee_listAccounts', 'e2ee_invite', 'e2ee_revoke',
  'attache_decrypt', 'attache_encrypt', 'attache_exportKeys',
  'readDocumentText', 'readDocumentData',
  'fullSnapshot_push', 'fullSnapshot_info', 'fullSnapshot_listVersions',
  'fullSnapshot_readCurrent', 'fullSnapshot_readVersion',
] as const
